# Generated by Django 4.2.4 on 2023-08-13 03:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slave",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("last_seen", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_token",
                    models.TextField(blank=True, max_length=400, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlaveToken",
            fields=[
                (
                    "token",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                (
                    "slave",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token",
                        to="slave.slave",
                    ),
                ),
            ],
        ),
    ]
