# Generated by Django 4.2.4 on 2023-08-14 09:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("slave", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="assigned_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="joblock",
            name="lock_to",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                to="slave.slave",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="time_to_reassign",
            field=models.IntegerField(
                default=60, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
