# Generated by Django 4.2.4 on 2023-08-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_job_assigned_at_remove_job_assigned_to_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joblock",
            old_name="job_id",
            new_name="job",
        ),
        migrations.RenameField(
            model_name="jobresult",
            old_name="job_id",
            new_name="job",
        ),
    ]
