# Generated by Django 4.2.4 on 2023-08-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_jobresult_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresult",
            name="content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
